### ISSUE TITLE
scantailor won't import

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-x11#42] opened 2015-03-22 14:42 UTC
_From @AllanKinnaird on March 22, 2015 13:3_

Running brew doctor produces the error message 
Error: Failed to import: scantailor
version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string

brew install scantailor produces the same message, as does brew info scantailor
Note also that this package does not appear on braumeister.org

_Copied from original issue: Homebrew/homebrew#37958_

**Comment by zfisch** [comment] 2015-04-11 23:29
I experienced the same issue but ran `cd /usr/local/Library && git stash && git clean -d -f` and it cleared up. Not sure if they're related...

**Comment by DomT4** [comment] 2015-05-24 12:26
Can't reproduce here with the freshly-merged [Boost fixes](https://github.com/Homebrew/homebrew-x11/commit/4a4fcf695d2840958d8d95d1e080f9b0d8d0813d). Closing, but will reopen if someone else flags it as still an issue.

**Comment by AllanKinnaird** [comment] 2015-05-24 13:57
Thanks.

I’m still getting the error from brew doctor, and if I  try to install I get
~: brew install scantailor
Error: version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/resource.rb:158:in `detect_version'
/usr/local/Library/Homebrew/resource.rb:141:in `version'
/usr/local/Library/Homebrew/formula.rb:965:in `version'
/usr/local/Library/Formula/scantailor.rb:25:in `<class:Scantailor>'
/usr/local/Library/Formula/scantailor.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

It may have something to do with my scantailor.rb being the version of 30th November 2013 - it’s not changed by brew update.

I guess it doesn’t seem to be doing me any harm.

thanks again, anyway.

**Comment by DomT4** [comment] 2015-05-24 14:08
Anything flagged by `brew readall` or `cd $(brew --prefix) && git status`?

**Comment by AllanKinnaird** [comment] 2015-05-24 14:53
Yeah - I get:

~: brew readall
Error: problem in /usr/local/Library/Formula/scantailor.rb
version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string
~: 

and:

~: cd $(brew --prefix) && git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Library/Aliases/firefly
	Library/Aliases/hugs
	Library/Aliases/jslint
	Library/Aliases/rbx
	Library/Aliases/saga
	Library/Aliases/urxvt
	Library/Contributions/brew_fish_completion.fish
	Library/Contributions/cmd/
	Library/Contributions/manpages/
	Library/ENV/libsuperenv.rb
	Library/Formula/adobe-air-sdk.rb
	Library/Formula/agedu.rb
	Library/Formula/aplus.rb
	Library/Formula/apple-gcc42.rb
	Library/Formula/appledoc.rb
	Library/Formula/appswitch.rb
	Library/Formula/asymptote.rb
	Library/Formula/atari++.rb
	Library/Formula/authexec.rb
	Library/Formula/aws-iam-tools.rb
	Library/Formula/bcwipe.rb
	Library/Formula/bochs.rb
	Library/Formula/brainfuck.rb
	Library/Formula/cantera.rb
	Library/Formula/cardpeek.rb
	Library/Formula/catdoc.rb
	Library/Formula/cdf.rb
	Library/Formula/celt.rb
	Library/Formula/clam.rb
	Library/Formula/clusterit.rb
	Library/Formula/comparepdf.rb
	Library/Formula/connect.rb
	Library/Formula/curl-ca-bundle.rb
	Library/Formula/curlftpfs.rb
	Library/Formula/darner.rb
	Library/Formula/dart.rb
	Library/Formula/dbslayer.rb
	Library/Formula/ddd.rb
	Library/Formula/dgtal.rb
	Library/Formula/diffpdf.rb
	Library/Formula/dmenu.rb
	Library/Formula/dotwrp.rb
	Library/Formula/drush.rb
	Library/Formula/dsniff.rb
	Library/Formula/dwm.rb
	Library/Formula/dzen2.rb
	Library/Formula/easy-tag.rb
	Library/Formula/electric-fence.rb
	Library/Formula/erviz.rb
	Library/Formula/etcdctl.rb
	Library/Formula/fceux.rb
	Library/Formula/feh.rb
	Library/Formula/finch.rb
	Library/Formula/flex_sdk.rb
	Library/Formula/flume-ng.rb
	Library/Formula/flume.rb
	Library/Formula/fox.rb
	Library/Formula/freeglut.rb
	Library/Formula/freerdp.rb
	Library/Formula/fsv.rb
	Library/Formula/geany.rb
	Library/Formula/geda-gaf.rb
	Library/Formula/geeqie.rb
	Library/Formula/geomview.rb
	Library/Formula/gerbv.rb
	Library/Formula/gfortran.rb
	Library/Formula/ggobi.rb
	Library/Formula/giblib.rb
	Library/Formula/git-flow-clone.rb
	Library/Formula/glade.rb
	Library/Formula/gle.rb
	Library/Formula/gnumeric.rb
	Library/Formula/gnunet.rb
	Library/Formula/gobby.rb
	Library/Formula/gpredict.rb
	Library/Formula/grace.rb
	Library/Formula/graylog2-server.rb
	Library/Formula/gromacs.rb
	Library/Formula/gsmartcontrol.rb
	Library/Formula/gtk-chtheme.rb
	Library/Formula/gtksourceviewmm.rb
	Library/Formula/gtksourceviewmm3.rb
	Library/Formula/gtkwave.rb
	Library/Formula/guilt.rb
	Library/Formula/haskell-platform.rb
	Library/Formula/hatari.rb
	Library/Formula/hexchat.rb
	Library/Formula/hllib.rb
	Library/Formula/hugs98.rb
	Library/Formula/hwloc.rb
	Library/Formula/imake.rb
	Library/Formula/inkscape.rb
	Library/Formula/iulib.rb
	Library/Formula/jpeg2ps.rb
	Library/Formula/jscoverage.rb
	Library/Formula/jsl.rb
	Library/Formula/jstalk.rb
	Library/Formula/justniffer.rb
	Library/Formula/kerl.rb
	Library/Formula/kernagic.rb
	Library/Formula/kismet.rb
	Library/Formula/klavaro.rb
	Library/Formula/libdlna.rb
	Library/Formula/libspotify.rb
	Library/Formula/libusbx.rb
	Library/Formula/lmutil.rb
	Library/Formula/meld.rb
	Library/Formula/mesalib-glw.rb
	Library/Formula/mess.rb
	Library/Formula/metalua.rb
	Library/Formula/metasploit.rb
	Library/Formula/mit-scheme.rb
	Library/Formula/mlkit.rb
	Library/Formula/mlton.rb
	Library/Formula/mlxcc.rb
	Library/Formula/morse.rb
	Library/Formula/mpio.rb
	Library/Formula/mscgen.rb
	Library/Formula/msgpack-rpc.rb
	Library/Formula/mt-daapd.rb
	Library/Formula/mupdf.rb
	Library/Formula/mydumper.rb
	Library/Formula/mysqlreport.rb
	Library/Formula/newick-utils.rb
	Library/Formula/nlopt.rb
	Library/Formula/openfst.rb
	Library/Formula/pan.rb
	Library/Formula/pari.rb
	Library/Formula/pathfinder.rb
	Library/Formula/pcb.rb
	Library/Formula/pdf2image.rb
	Library/Formula/pdf2svg.rb
	Library/Formula/pgplot.rb
	Library/Formula/pixie.rb
	Library/Formula/pjsip.rb
	Library/Formula/play.rb
	Library/Formula/pngrewrite.rb
	Library/Formula/prooftree.rb
	Library/Formula/pyxplot.rb
	Library/Formula/qrupdate.rb
	Library/Formula/rdesktop.rb
	Library/Formula/rxvt-unicode.rb
	Library/Formula/saga-core.rb
	Library/Formula/salt.rb
	Library/Formula/scalate.rb
	Library/Formula/scantailor.rb
	Library/Formula/scrotwm.rb
	Library/Formula/shark.rb
	Library/Formula/sitecopy.rb
	Library/Formula/slicot.rb
	Library/Formula/smartsim.rb
	Library/Formula/solfege.rb
	Library/Formula/sundials.rb
	Library/Formula/swi-prolog.rb
	Library/Formula/sxiv.rb
	Library/Formula/sylpheed.rb
	Library/Formula/tabbed.rb
	Library/Formula/tcpurify.rb
	Library/Formula/tetgen.rb
	Library/Formula/texmacs.rb
	Library/Formula/tiger-vnc.rb
	Library/Formula/tmap.rb
	Library/Formula/transmission-remote-gtk.rb
	Library/Formula/ume.rb
	Library/Formula/upnp-router-control.rb
	Library/Formula/urweb.rb
	Library/Formula/ushare.rb
	Library/Formula/viewglob.rb
	Library/Formula/wkhtmltopdf.rb
	Library/Formula/wmctrl.rb
	Library/Formula/x3270.rb
	Library/Formula/xar.rb
	Library/Formula/xchat.rb
	Library/Formula/xclip.rb
	Library/Formula/xdotool.rb
	Library/Formula/xpa.rb
	Library/Formula/xpdf.rb
	Library/Formula/xplot.rb
	Library/Formula/xspringies.rb
	Library/Formula/yarp.rb

nothing added to commit but untracked files present (use "git add" to track)
local: 

(I’ve only ever used the ordinary brew commands - install, update, upgrade, cleanup, doctor and prune, so there shouldn’t be anything odd about my Homebrew installation.)

**Comment by DomT4** [comment] 2015-05-24 15:15
Let's do `cd $(brew --prefix) && git fetch; git reset --hard origin/master` to fix the latter issue, and then see if `brew readall` is still unhappy afterwards.

**Comment by AllanKinnaird** [comment] 2015-05-24 15:24
I’m afraid it is!

~: cd $(brew --prefix) && git fetch; git reset --hard origin/master
HEAD is now at 1f2c606 slimerjs: fix head build
local: brew readall
Error: problem in /usr/local/Library/Formula/scantailor.rb
version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string
local:

and git status gives the same message as before.

**Comment by DomT4** [comment] 2015-05-24 15:30
Funky. What's your `brew config`?

**Comment by AllanKinnaird** [comment] 2015-05-24 15:34
local: brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1f2c60618edc2f947fbc2ca8d1f9378d2b428b2b
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: 1.8.0_25
local:

**Comment by AllanKinnaird** [comment] 2015-05-24 21:17
Hi Dominyk

Totally off thread (!) - I got a bit panicky when I saw that Homebrew had removed Lilypond, required for my Frescobaldi, but I soon tracked it down, thanks to your impeccable documentation.

I have to say that for years I have been blown away by the commitment and effort you guys put into this work.

I feel I would like to contribute also. Some time ago i was, I think, the best debugger in Marconi Instruments (RIP!) and have contributed a few creative advances over the decades (Once I built a railroad…!). I have worked in FORTRAN, ALGOL, ATLAS (military test language), Pascal, BASIC, C, C++ (not so much!), xBase, SQL, Ruby, Java, Javascript, PHP (a little), PERL (a little), Python, LISP (a little) and probably touched on a few others, not to mention several assemblers, a little bit of microcode for AMD bitslice machines, and writing floating point trig routines (in octal code if I remember) for the four-bit register Rockwell SC/MP. I would say one of my strengths is being able to pick up languages quickly. As well as being a bloody good debugger!

If you guys have some non-critical low-priority task (you never know, I may be useless!) you’d like to farm out, I would be interested to hear about it.

Allan

**Comment by DomT4** [comment] 2015-05-25 22:03
Very odd. I wondered if you were using an extremely old Ruby or something, but evidently that's not the case. Any idea here @jacknagel? I can't reproduce this locally using the same Ruby/OSX/etc.

@AllanKinnaird Thanks for the kind words. Yeah, we moved Lilypond to the `tex` tap - We've been trying to move more things that require non-Homebrewed dependencies out of the core.

If you're interested in contributing the best way to do so is to find things that need fixing and then tee up PRs to fix them. If you're feeling particularly adventurous there's various Issues and PRs tagged with the `Features` tag in Homebrew/homebrew that often require some TLC.

One of the things that also needs doing for a lot of formulae is having `test do` blocks added to them, preferably with a "real" test rather than `bin/"example", "--version"` or similar. PRs that add decent tests to formulae do get merged.

**Comment by AllanKinnaird** [comment] 2015-05-25 22:24
Thanks Dominyk  - what if I were simply to delete my existing version of scantailor.rb? If it gets correctly regenerated it wouldn’t explain why the problem arose :-( but might stop my brew doctor error? I must admit I’d rather identify the root cause! Anything more I can do to help? I suppose I could copy the existing version and then delete it, so I could (maybe?) restore the current state later - I’m not too clued up on the nuts and bolts of the process.

**Comment by jacknagel** [comment] 2015-05-25 23:01
There must be an older version of the scantailor formula present, which used to specify its version as a hash (but this feature no longer exists). It's not removed by `git reset --hard`, because that file is no longer tracked in the main repository. I would do the following:

```
cd $(brew --repository)
git ls-files -o -- Library/Formula | xargs rm
```

That should remove any untracked files in the formula directory.

**Comment by AllanKinnaird** [comment] 2015-05-26 10:13
That cleared the scantailor error message in brew doctor, but raised a new one - “No available formula for lilypond”.

Seems like the alias in Library/Formula for lilypond.rb (now in Library/Taps/homebrew/homebrew-tex/Formula ) is untracked and got deleted along with the rest. Should I do something about that or is it actually a bug I should report?

**Comment by DomT4** [comment] 2015-05-26 18:08
If you don't already have `homebrew/tex` tapped, `brew tap homebrew/tex` may fix it. If you already have it tapped, try `brew tap --repair`. https://github.com/Homebrew/homebrew/pull/40106 should shake loose the last warning about expecting to find a Lilypond dep in the core, which may be the cause here as well.

**Comment by AllanKinnaird** [comment] 2015-05-26 19:12
brew tap --repair seems to have fixed the problem.

Thanks.

**Comment by DomT4** [comment] 2015-05-26 19:21
Great! All seems to be fixed here, so closing :tada:.

**Closed by DomT4** 2015-05-26 19:21 UTC
