### ISSUE TITLE
Recent formula deletions

### ISSUE THREAD

**Issue by larryhynes** [Homebrew/homebrew-x11#285] opened 2017-01-10 00:44 UTC
Hi

A series of recent commits, on December 30th last, removed 21 formulas from homebrew-x11, including such luminaries as [dmenu](https://github.com/Homebrew/homebrew-x11/commit/3eed69f233c4249bd2e10f4eb9294202faaef7bf),  [sxiv](https://github.com/Homebrew/homebrew-x11/commit/af6ecf1c10fd555708b2ca6f607b8275ca7afd5f) and [cwm](https://github.com/Homebrew/homebrew-x11/commit/59e843f9399670245868b582b048257439aae13d).

All the commits bear the same "delete unused formula" commit message. Can I ask, what constitutes 'unused'? (I submitted an update to the [sxiv formula](https://github.com/Homebrew/homebrew-x11/commit/52372d941b4c9f77fc4962ec5c6f342fd9b62309) on 6th December, and I'm still using it - yet 24 days later it's removed as 'unused'.)

Of particular concern is the removal of [i3status](https://github.com/Homebrew/homebrew-x11/commit/d48c5fa784a5dafb369c9a483fc57be2ac7340d4), which is a companion to [i3](https://github.com/Homebrew/homebrew-x11/blob/master/i3.rb); if - and I hope it is - i3 is to be kept, is it not reasonable to keep i3status?

I appreciate that X11 on the mac may be a 'niche' to some, but it is very much 'front and centre' of my computing. If (not) maintaining the formulas in homebrew-x11 is a question of manpower, you may consider me volunteered; just point me at some work.

Is there a 'roadmap' that might outline future removal plans, that can be shared and - hopefully - debated?

Is there a commitment to supporting X11 on the mac by homebrew in the future? If not, is homebrew willing to reexamine this decision, or share how and when the decision was reached?

Are the homebrew-x11 maintainers open to any compromise on these removals?

**Comment by woodruffw** [comment] 2017-01-10 05:56
The short answer is that X11 is basically a second-class citizen on OS X (as I'm sure you're aware), and that maintaining relatively-unused X11 formulae takes time away from formulae that are downloaded much more frequently and are more integrated into OS X itself.

There's no particular roadmap for removals (as far as I'm aware, anyways) - they get removed based on our analytics numbers and experience with maintenance. If you've opted out of analytics or know people who have who also use X11 packages, *please* opt back in - those figures factor heavily into removal decisions.

I think we should reconsider the removals of `dmenu` and `i3status` at first glance - they're common packages on other systems and are an integral part of `i3`. Pinging @MikeMcQuaid on that - my bet is that the groups that are installing these packages are the ones that tend to opt-out of analytics.

Ultimately, however, the future of X11 on OS X is perpetually unclear and only represents a portion of Homebrew users. My personal advice is to move some of your required X11 formulae into a personal tap to avoid breakage caused by future removals.

**Comment by ilovezfs** [comment] 2017-01-10 08:41
The future is probably a third-party tap.

**Comment by larryhynes** [comment] 2017-01-10 13:32
Thanks William

I like to think of X11 as a first-class citizen which occupies second place; Apple do commit resources to it and @jeremyhu does sterling work in keeping that flame alive. XQuartz has behaved flawlessly for me over many versions, and could even be considered a good example of a company and community working together.

Yes, I opted out of analytics as soon as I one day noticed, that someone had - without asking - placed some sort of Google-related file on my local disk. That was the first I saw or heard of Homebrew analytics, and it will be the last. It's also a whole other discussion. ;)

(One would imagine that the rather obvious 'analytic' of someone submitting an updated version of a package a couple of weeks before its removal would raise a flag, as in my case with sxiv?)

The removal of 21 formulae at one swipe would not look out of place in the entire homebrew ecosystem, but in the context of homebrew-x11 it is akin to an extinction-level event, leaving only 37 formulae in its wake. It also appears to be have been ill-considered since, as you acknowledge, i3status is an integral part of i3. I would hope that - at a minimum - i3status and dmenu (and sxiv!) would make a reappearance. (sxiv is a really great tool, compiles easily, and is something I would never have known about if it wasn't for its formula here.)

My ticket included an offer of time. I have also [previously offered](https://github.com/Homebrew/homebrew-x11/issues/163) time to the project. These offers tend to go unacknowledged, so I'm acknowledging it here myself, and making it again: if you need time or help in maintaining these formulae, I will step in, to the best of my ability. It is unclear to me how one goes about becoming a maintainer or volunteer with homebrew, if you have any pointers? I think it would be preferable for these formulae to stay right here and be maintained as part of homebrew, rather than as part of a third party tap. Like, wouldn't the time it would take me to maintain a tap be better spent maintaining homebrew-x11, for everyone's sake?

**Comment by MikeMcQuaid** [comment] 2017-01-10 14:17
@woodruffw and @ilovezfs's comments are correct and I agree with them all. I'm happy to consider re-adding specific formulae on request if you can list the ones you wish us to do do. Longer-term the plan is to fold almost all the Homebrew/homebrew-* taps back into Homebrew/homebrew-core and things that would not be accepted there as new formulae (which includes most of this tap) will not be migrated. 

> My ticket included an offer of time.

In that case, we'll consider taking you up on your offer and migrating these formulae to a third-party tap you control. I apologise that your offers previously have gone unacknowledged; this tap has been ignored by many of the maintainers (including me) due to the reasons I've stated above which is another strong argument for why we need to consolidate taps again.

> I would hope that - at a minimum - i3status and dmenu (and sxiv!) would make a reappearance. (sxiv is a really great tool, compiles easily, and is something I would never have known about if it wasn't for its formula here.)

I've readded these as-of 284a081. Let me know others you personally use and would like to see re-added.

> Yes, I opted out of analytics as soon as I one day noticed, that someone had - without asking - placed some sort of Google-related file on my local disk. That was the first I saw or heard of Homebrew analytics, and it will be the last. It's also a whole other discussion. ;)

No Google-related files were ever put on your disk. We ran `uuidgen` (as provided by macOS) to get a unique user ID which cannot be linked to you in any way. As noted by [the analytics documentation](http://docs.brew.sh/Analytics.html) opting-out of analytics is well within your rights but that also means that effectively we discount your usage when making decisions like this.

**Comment by larryhynes** [comment] 2017-01-10 16:33
Thanks Mike

> things that would not be accepted there as new formulae (which includes most of this tap)

Personally, I think this is a shame, but I don't make the rules so God speed with this and all your endeavours.

Thank you for restoring the three formulae sxiv, i3status and dmenu. I hope you consider the restoration of i3status, at the very least, as 'the right thing' in this case and not just something I use and made a fuss about. However inconvenient one's users may be, they are still one's users, and are opt to do silly things like run X11 on a Mac. I would like to think the restoration of these formulae will make it easier for some young fool to experiment with their Apple computer and, perhaps, open some doors for them, as it did for me.

> No Google-related files were ever put on your disk.

As I alluded to above, this is a whole different discussion, not one I intended to have, one I deliberately stayed out of at the time, and one that I assume has been had 'to death'. If you have the time and inclination to discuss this further, please drop me an email to larry@larryhynes.com and I will be happy to explore it with you - I don't think the issue at hand, the recent deletion of 21 formulae, and what it might mean for the future of homebrew's support for X11 on the Macintosh, is served by any further discussion of the analytics brouhaha here. I do note, and accept, that opting out of Homebrew's current analytics programme means that my usage does not appear in the analytics report, and I will continue to make the point that someone updating a formula 24 days before you decide to nix that formula is a pretty big indicator that that formula is not 'unused', analytics or no analytics.

> In that case, we'll consider taking you up on your offer and migrating these formulae to a third-party tap you control.

Is this the best advice you can give to someone who wishes to volunteer with the project, and who has explicitly asked for information on how to volunteer with the project?

**Comment by ilovezfs** [comment] 2017-01-10 17:19
>Is this the best advice you can give to someone who wishes to volunteer with the project, and who has explicitly asked for information on how to volunteer with the project?

If you're talking about non-X11-related volunteering, I'd advise looking at the user issues and feature/formula requests in https://github.com/Homebrew/brew/issues and https://github.com/Homebrew/homebrew-core/issues, and seeing if there are any you can resolve either by talking with the user or by opening a PR. Also, if there's a feature or formula you yourself want to see added, opening a PR would be great, and we're happy to iterate with you on the PRs until they're ready to be merged to master.

If you're talking about specifically X11-related volunteering, Mike's point that "we'll consider taking you up on your offer and migrating these formulae to a third-party tap you control" was not meant tongue-in-cheek. This is exactly the approach we pursued with the deprecation of Qt 4, and cartr generously offered to adopt the Qt 4 formula and its dependents in https://github.com/cartr/homebrew-qt4.

If it's a foregone conclusion that the X11 tap will be deprecated, possibly with a few of the most popular formulae imported into homebrew/core, then indeed the formulae from the tap will be looking for a happy and healthy home with a third party, which would be preferable to shipping them off to the boneyard https://github.com/Homebrew/homebrew-boneyard.

**Comment by MikeMcQuaid** [comment] 2017-01-10 19:25
@larryhynes I'm sorry I wasn't more helpful. I replied at 5am while on a work trip because I wanted to try and get you some sort of reply ASAP. @ilovezfs has provided some good starting points but I'll get you a more in-depth reply soon.

**Comment by larryhynes** [comment] 2017-01-10 20:12
Absolutely no problem, Mike, I have plenty to go on from @ilovezfs 's suggestions. Feel free to close this, I'll start looking into the care and feeding of one's own brew tap and follow up on the other suggestions.

**Closed** 2017-01-10 20:58 UTC

**Comment by MikeMcQuaid** [comment] 2017-01-16 19:23
> Is this the best advice you can give to someone who wishes to volunteer with the project, and who has explicitly asked for information on how to volunteer with the project?

@larryhynes There's three places to look for things that you could work on (in ascending difficulty):

- [The "Contributing" section of the Homebrew/brew README](https://github.com/Homebrew/brew#contributing) i.e. run `brew audit --strict` and fix things
- [`help wanted` issues on Homebrew/homebrew-core](https://github.com/homebrew/homebrew-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- [`help wanted` issues on Homebrew/brew](https://github.com/homebrew/brew/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

Let me know if you want help getting started on any of them or if you'd like me to suggest stuff more specifically based on interest or ability.

Thanks for offering to help!
